CREATE TABLE IF NOT EXISTS client (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(1000),
    email VARCHAR(300) UNIQUE
);

CREATE TABLE IF NOT EXISTS favoriteProduct (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    clientId INT,
    productId INT,
    UNIQUE(clientId, productId),
    FOREIGN KEY (clientId) REFERENCES client(id) ON DELETE CASCADE
);
